### ISSUE TITLE
Path initialization is missing layer parameter

### ISSUE THREAD

**Issue by amatherbishop** [heitzmann/gdspy#126]
In Polygon.py, the class Path __init__ function doesn't allow the path layer(s) to be set.

**Comment by heitzmann** [comment]
@amatherbishop That's because in [`Path`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.Path), each piece can have a different layer and datatype. Look at [`Path.segment`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.Path.segment) or [`Path.turn`](https://gdspy.readthedocs.io/en/stable/reference.html#gdspy.Path.turn), for example.
