### ISSUE TITLE
EBL

### ISSUE THREAD

**Issue by weimaoliang** [heitzmann/gdspy#140]
When I used the EBL mask generated by gdspy, the splice between polygons broken after EBL procedure. However, there is no gap between the polygon in gdsii file. The EBL machine we used is Raith Voyager. Have you meet with this trouble and how can I solve this problem?
![1](https://user-images.githubusercontent.com/30894363/86562943-21208380-bf96-11ea-83bb-b26c2b8f3968.png)

**Comment by heitzmann** [comment]
@weimaoliang I have not had this issue before, but you could try a few things. First, leaving the splice away from the gap region might help. Second, check you fractured geometry to see if the beam pattern correctly exposes the splice region. Lastly, you can verify the order in which exposure happens to make sure the whole ring is exposed as quickly as possible to minimize errors caused by drifting of the electron beam.
