### ISSUE TITLE
Circle drawing behaviour at small sizes

### ISSUE THREAD

**Issue by JamesWhitehead5** [heitzmann/gdspy#149]
**System specs**
gdspy version: 1.6
Python version: 3.7.4
OS: MacOS 10.13.6
CPU: Intel(R) Core(TM) i5-5350U

**Current behavior**
This issue contains two, likely related, bugs concerned with drawing circular polygons.

When drawing circles where the radius is close to the library precision, there seems to be some (unexpected?) behavior in terms of rounding.

Here is a simple program that draws an array of circular polygons:

```python
import gdspy

lib = gdspy.GdsLibrary(unit=1e-6,  precision=1e-6)
main = lib.new_cell("circle_radius_sweep")

# generate circles with radii near the library precision
r_max = 50 # maximum circle radius (exclusive)
radii = range(1, r_max)
for i, radius in enumerate(radii):
  cell = lib.new_cell('cir_r_%02d' % radius)
  cell.add(
    # parameters use length units defined when library was initialized
    gdspy.Round((0, 0), radius, tolerance=0.01)
  )
  main.add(gdspy.CellReference(cell, (2*r_max*i, 0)))

lib.write_gds("out.gds")
```

Program output
![image](https://user-images.githubusercontent.com/43419285/91338669-23c77a00-e78a-11ea-9dc9-6ba9128ec4d6.png)

Circular polygon (radius: 3 library precision units, tolerance: 0.01):
![image](https://user-images.githubusercontent.com/43419285/91336296-90407a00-e786-11ea-96f6-a9354b1e251a.png)
This asymmetry is noticeable with several other small radii, but most are symmetric. Should circular polygons always be x and y symmetric regardless of radius and tolerance? While is behavior is a nuance of this tool, I'm not convinced that this is a bug. I just want to make sure that it is documented here so the author can make that decision.

Edit: After using another GDSII editor and checking the coordinates, the second issues seems to be an issue with the rendering of my GDSII editor (Layout Editor), not this library.
~~I decided to try some different values for the tolerance parameter and it looks like I found an actual bug here though.
I tried a tolerance value of 0.001.
This seems to have made the circles x and y symmetric for small radii, but there are some artifacts that creep up at the larger radii.
![image](https://user-images.githubusercontent.com/43419285/91338337-a13eba80-e789-11ea-8559-69e026f99d3e.png)
I assume that the splitting of the circular polygons into sub-polygons is necessary to keep the number of points per a polygon within the GDSII specification. However, there are gaps where the polygons meet for some circles.~~

**Impact**
For the non-symmetric drawing of circles issue, users can just create their own circular polygon generation tools using the polygon method in this library if it is important to them. Overall, not a significant issue in my opinion.
~~For the drawing of circles with small tolerances where gaps emerge between the segments, this could be a significant issue.~~

**Comment by heitzmann** [comment]
@JamesWhitehead5 Thank you for your report. Indeed, the issue you find with the small circles in you code sample is expected and it is because of vertex rounding to the closest integer (considering the unit and precision).

Vertex rounding uses `numpy.round(vertex * precision / unit)`. The choice of `unit == precision` is definitely not usual: it will round all vertices to integer values, so writing any shape of (close to) unit length will result in strong deformations.

If you change `precision` to 1e-9 in your example, the shapes go back to what you would expect from a circle, because they will retain 3 decimal places of precision after rounding.

You can read a more comprehensive explanation about the significance of `unit` and `precision`, take a look [at this section](https://gdspy.readthedocs.io/en/stable/gettingstarted.html#units-in-gdsii) of the tutorial.
