### ISSUE TITLE
Exporting to gds by layer

### ISSUE THREAD

**Issue by syshah86** [heitzmann/gdspy#20]
Hello Lucas,

I am looking for a way to export to gds specific layers from a larger gds file. Alternatively, is there a way to import only a particular layer using gds_import?

Shreyas Shah

**Comment by heitzmann** [comment]
I don't think there is a straightforward way to do that. Gdspy does not have tools to easily modify GDSII files, only to create, so it's probably easier to import the file and instead of extracting any number of cells to the new one, you can loop over every cell/polygon and copy to a new CAD the ones you want.
