### ISSUE TITLE
In next: Label rotation and magnification not responding to arguments.

### ISSUE THREAD

**Issue by dwaardenburg** [heitzmann/gdspy#84]
Dear L. Heitzmann,

I am unable to rotate my labels by changing the argument.

A snippet of the code I have:
resonator_label = gdspy.Label('Index: ' + str(resonator_frequencies.index(sorted_frequencies[i])) + ' frequency: ' + str(resonator_frequencies[i] / 1e9) + ' GHz', (bounding_box_x, bounding_box_y), 'o', rotation = 45, layer = labels_layer)

Let me know if it is my mistake :P

Kind regards,

Daan

**Comment by heitzmann** [comment]
Hello Daan, your code is correct.
The problem is that LayoutViewer doesn't support displaying labels with rotation due to a limitation in the Tkinter Canvas widget. From my experience, KLayout doesn't support this either.

Just to make sure the gdsii file is correct, I did a simple example and checked the hexdump: the rotation information is the sequence in bold.

```python
import gdspy
gdspy.Cell('test').add(gdspy.Rectangle((0, 0), (1, 1))).add(gdspy.Label('text', (0, 0), 'o', rotation=45))
gdspy.write_gds('labeltest.gds')
```

<pre>hexdump -C labeltest.gds

00000000  00 06 00 02 02 58 00 1c  01 02 07 e3 00 04 00 08  |.....X..........|
00000010  00 0a 00 0c 00 20 07 e3  00 04 00 08 00 0a 00 0c  |..... ..........|
00000020  00 20 00 0c 02 06 6c 69  62 72 61 72 79 00 00 14  |. ....library...|
00000030  03 05 3e 41 89 37 4b c6  a7 f0 39 44 b8 2f a0 9b  |..>A.7K...9D./..|
00000040  5a 54 00 1c 05 02 07 e3  00 04 00 08 00 0a 00 0c  |ZT..............|
00000050  00 20 07 e3 00 04 00 08  00 0a 00 0c 00 20 00 08  |. ........... ..|
00000060  06 06 74 65 73 74 00 04  08 00 00 06 0d 02 00 00  |..test..........|
00000070  00 06 0e 02 00 00 00 2c  10 03 00 00 00 00 00 00  |.......,........|
00000080  00 00 00 00 00 00 00 00  03 e8 00 00 03 e8 00 00  |................|
00000090  03 e8 00 00 03 e8 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 04 11 00 00 04  0c 00 00 06 0d 02 00 00  |................|
000000b0  00 06 16 02 00 00 00 06  17 01 00 05 00 06 1a 01  |................|
000000c0  00 00 <b>00 0c 1c 05 42 2d  00 00 00 00 00 00</b> 00 0c  |......B-........|
000000d0  10 03 00 00 00 00 00 00  00 00 00 08 19 06 74 65  |..............te|
000000e0  78 74 00 04 11 00 00 04  07 00 00 04 04 00        |xt............|
000000ee
</pre>
