### ISSUE TITLE
Set the max_points to 4

### ISSUE THREAD

**Issue by JunlingLong** [heitzmann/gdspy#88]
Hi,

I am trying to break down all my polygons to 4-point- or 3-point-polygons. This is required to prepare a input file corresponding to my gds design in Fastercap. However, GDSpy require max_points to be more than 4 to fracture the polygon. Is there anyway to allow the max_points to be set to 4?

Thanks,
Junling

**Comment by heitzmann** [comment]
Hi @JunlingLong,

Unfortunately that is not possible because we slice polygons along vertical and horizontal lines only (which requires more than 4 vertices for a general solution). What you need is a polygon triagulation/tesselation tool—something the generates a triangular or quadrangular mesh based on your polygon. There should be python libraries out there that can perform this operation. For triagulations, take a look into [Scipy's Delaunay triagulation](https://docs.scipy.org/doc/scipy/reference/tutorial/spatial.html). It might be enough for you use case.

Once you mesh all your polygons than you can create `gdspy.Polygon` or `gdspy.PolygonSet` from them.
